public class SecScanFindingDTO {

    public String checkId            { get; set; }
    public String checkName          { get; set; }
    public String category           { get; set; }
    public String categoryCode       { get; set; }
    public String severity           { get; set; }
    public String findingType        { get; set; }
    public String affectedComponent  { get; set; }
    public String affectedComponentType { get; set; }
    public String description        { get; set; }
    public String impact             { get; set; }
    public String remediation        { get; set; }
    public String rawEvidence        { get; set; }
    public String salesforceDocUrl   { get; set; }
}
